### ISSUE TITLE
Customize Styles for the OneGraph GraphiQL Explorer

### ISSUE THREAD

**Issue by dwwoelfel** [OneGraph/onegraph-changelog#27]
Our open-source GraphiQL Explorer library just got support for custom styling. 

You can provide custom colors, customize the button styles, and provide custom components for the checkboxes and arrows. Read more about [how to customize the styles on the README](https://github.com/OneGraph/graphiql-explorer#customizing-styles).

We've been happy to see companies that use GraphQL adopt the explorer (see [Gatsby]( https://www.gatsbyjs.org/blog/2019-06-03-integrating-graphiql-explorer/), [Shopify]( https://help.shopify.com/en/api/graphql-admin-api/graphiql-explorer), [AWS Amplify](https://aws.amazon.com/blogs/mobile/amplify-framework-local-mocking/), [PostGraphile](https://twitter.com/benjie/status/1090570495815241728?lang=en), [Hasura](https://github.com/hasura/graphql-engine/pull/1680), [GraphiQL Online](https://github.com/hasura/graphql-engine/pull/2737), and [GraphiQL.app](https://github.com/skevy/graphiql-app/pull/152)).

With this change, we expect to see a few more come on board. If you'd like help integrating the explorer, email [sayhi@onegraph.com](mailto:sayhi@onegraph.com) or [hop into our Spectrum channel](https://www.onegraph.com/chat).

**Comment by sgrove** [comment]
Great addition! This'll help Hasura, Altair, and quite a few others for sure. Excited to see the explorer rolled out even wider now that it's so easy to style!
